ТЗ-15
LenzFF/java-shareit pull request #4
Opened 2023-06-24 13:58 UTC by LenzFF

Итерация 1

2023-06-24 20:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>              throw new DataNotFoundException("Пользователь не может забронировать свою вещь, id - " + userId);
Минорное - логичней что-то типа IllegalDataException

2023-06-25 07:40 UTC, db-exp requested changes

2023-06-25 07:40 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
>  public interface CommentRepository extends JpaRepository<Comment, Long> {
не хватает аннотации Repository

2023-06-25 07:40 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>      private final UserRepository userStorage;
напомню - лучше для меньшей связности из сервисов использовать "чужие" сервисы, а не репозитории

2023-06-25 07:40 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    private String description;
Можно еще Size добавить

2023-06-25 07:40 UTC, db-exp commented on src/main/resources/schema.sql
>    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
например, в UserDto long, а тут integer. Лучше привести все типы id к одному

2023-06-25 07:40 UTC, db-exp commented on src/main/resources/schema.sql
>    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
private Long id; в модели

2023-06-25 07:40 UTC, db-exp commented on src/main/resources/schema.sql
>    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
private long id; в модели

2023-06-25 10:11 UTC, LenzFF commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
>  public interface CommentRepository extends JpaRepository<Comment, Long> {
так она там есть ;)

2023-06-25 10:30 UTC, LenzFF commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>      private final UserRepository userStorage;
Согласен! 
Можно оставлю на следующий проект?) 
Сейчас уже слишком много переделывать, а сроки горят)
Уже если менять, то везде...

2023-06-25 14:57 UTC, db-exp approved these changes

2023-06-25 15:09 UTC, merged